name: Build and push to Docker Hub

on: push

env:
  IMAGE_NAME: base-debian
  DOCKER_REGISTRY_URL: 3dpro
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  setup-build-publish-deploy:
    name: Setup, build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Configure Docker to login to Docker Hub
      - run: |-
          docker login --username "$DOCKER_REGISTRY_USERNAME" --password "$DOCKER_REGISTRY_PASSWORD"

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "$DOCKER_REGISTRY_URL/$IMAGE_NAME" \
            .

      # Push the Docker image to Image Registry
      - name: Publish
        run: |-
          docker push "$DOCKER_REGISTRY_URL/$PROJECT_NAME/$IMAGE_NAME"
